### PR TITLE
Fix and add new tests (#786, #824)

### LINKED ISSUE #786: Remove test that mocks devtools::add_path()
`devtools::add_path()` does not exist in current devtools (https://github.com/r-lib/devtools/commit/dbf00241ec0a48ea1a19e7c96be2ace21d7e726d) and this test mocks it and therefore fails for me:

https://github.com/r-lib/testthat/blob/1faa32fc1afa769ac16bdb5792fd597324143c57/tests/testthat/test-mock.R#L81-L87

I can't decide if this test should be deleted or modified, so will not make a PR to fix this.

### PR DESCRIPTION
**Pull request by patr1ckm**
This adds a few more tests, addressing some of the low coverage areas and untested branches from the codecoverage report.

Would more contributions in this vein be appreciated? It would be fun to tackle more of the low coverage areas, but it will probably require more testing code. 

Fixes #786, #824

### CODE REVIEW

**Comment by patr1ckm** [comment]
The tests are now compatible with the new version of devtools.

## Fixed Errors
There was one new error, as noted in #786. This was fixed by mocking a different function from devtools instead of `devtools::add_path` which was removed. I chose `devtools::document` because it was unlikely to be removed.

## Fixed Warnings
There were two new warnings in `testthat/test_catch.R`. To fix I needed to do the following:

- Set `R_TESTS=''`. This fix may be a result in a change in behavior upstream but I'm not sure.
- Replace `devtools::create` with `usethis::create_package`. I added `usethis` to `Suggests` as a result.

Because I was unable to debug these warnings when the `test_catch` messages were suppressed, I left them on in case errors in `test_catch` surface again. However, I can make `test_catch` run quietly again if you prefer.

**Comment by kevinushey** [comment]
The Catch-related test changes look fine to me.

**Comment by hadley** [comment]
Thanks - can you please merge with changes to master? I think the conflicts come because we fixing the mocking failure in a different way to you.

**Comment by hadley** [comment]
Thanks @patr1ckm !

**Pull request merged**
