### PR TITLE
Typo: check_repoter

### PR DESCRIPTION
**Pull request by mlysy**
4 instances changed in 3 files.

### CODE REVIEW

**Comment by krlmlr** [comment]
Can you please run `devtools::document()` so that the changes are reflected in the documentation?

**Comment by mlysy** [comment]
Thanks for the feedback.  I fixed those files, but then also had to change all files in `tests/testthat/reporters` to remove errors of the form:
```
`test_reporter(reporter)` has changed from known value recorded in 'reporters/check.txt'.
```
Now I'm getting a different error with `codecov/patch`.  This is all a bit new to me...can you please advise on how to fix this?

**Comment by hadley** [comment]
You can ignore the codecov failures.

But unfortunately it looks like your changes got tangled up with the restyling. Do you want to have another go? (If you don't, I'm happy to do it)

**Comment by mlysy** [comment]
Thanks for letting me ignore codecov.

I think other than that the conflicts have been resolved...please let me know if I can do anything else.

**Comment by jmarca** [comment]
Just noticed this typo myself.  Is this PR going to be merged? Does anything more need to be done?

**Comment by jimhester** [comment]
Thanks! I ended up fixing this in https://github.com/r-lib/testthat/commit/70b86a990cb9f7ae77d2139e69c62cc5cceb88bc and https://github.com/r-lib/testthat/commit/25d33256e147378f77245ccba963ee040587637a

**Pull request closed without merging**
