### PR TITLE
In CheckReporter, also display summary at top

### PR DESCRIPTION
**Pull request by hadley**
This is useful when look at the full results in CI

### CODE REVIEW

**Review by gaborcsardi — COMMENTED** [review]
Should we add some optimization to avoid showing the summary twice if there is no other output? I.e. if there are no skips, warnings, errors, etc. at all?

**Comment by hadley** [comment]
I thought about that but couldn't be bothered since it seems unlikely to come up that much.

**Comment by gaborcsardi** [comment]
It comes up for every clean test suite, no?

Not a big deal, just a weird to have this duplication.

```
> library(testthat)
> library(pingr)
>
>  test_check("pingr")
[ FAIL 0 | WARN 0 | SKIP 0 | PASS 21 ]

[ FAIL 0 | WARN 0 | SKIP 0 | PASS 21 ]
>
> proc.time()
   user  system elapsed
  0.297   0.085   3.724
```

**Comment by hadley** [comment]
Oh I see what you mean. I guess I was just thinking about the actions, where you only ever look at this display if there are test failures.

**Comment by hadley** [comment]
I'll fix momentarily (`if (self$skips$size() || self$warnings$size() || self$problems$size()))`

**Pull request merged**
