### PR TITLE
Don't run a single file in parallel

### PR DESCRIPTION
**Pull request by hadley**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
I am not sure about this. 

It is true that performance-wise it does not make much sense to run a single test file in a subprocess. (OTOH it is not much slower, either, usually.) 

I chose to run even a single file "in parallel" to make tests more reproducible. Especially when working on a single test file, it is easy to get into a situation where this test file works fine in the main process, but it does not work in the subprocess.

**Comment by hadley** [comment]
One of the reasons I like running individual test files is that you can put a `browser()` in where needed; that obviously doesn't work any more.

**Comment by gaborcsardi** [comment]
Yeah, that makes sense. When you do that, do you use `test_file()` or `test(filter = ...)`? Maybe it would make sense not to run `test_file()` in parallel, only `test(filter = ...)`, regardless of how many files the latter one selects?

**Comment by hadley** [comment]
Well I call `devtools::test_file()` which calls `testthat::test()` with `filter` set 😬

**Comment by gaborcsardi** [comment]
Oh, right. Well, then there are two ways to go I guess.

1. We do not merge this PR, and if you want interactive debugging, then you do `Sys.setenv(TESTTHAT_PARALLEL = "FALSE")`. (Or use the Debug reporter.)
2. We do merge this PR, and then if people want to run a single test file in a sub-process, they'll do `Sys.setenv(TESTTHAT_PARALLEL = "TRUE")`.

**Comment by hadley** [comment]
Looks like I need to patch devtools for #1286, so I can just make it call `test_file()` instead.

**Comment by hadley** [comment]
`test_file()` already relies on the default value of `parallel` (FALSE) so there's nothing more to do here.

**Pull request closed without merging**
