### PR TITLE
Snapshot files have .new variants too!

### LINKED ISSUE #1462: `new` `expect_snapshot_file()` files are being removed
When I run a test and an updated `expect_snapshot_file()` output is found, the _new_ file is removed at the end of calling `devtools::test()`. I would expect the _new_ file to remain after testing is completed.

If `devtools::test(filter=)` is used, the _new_ snapshots are not deleted. 

(I do not know if this bug extends to other snapshot functions.)

Reprex:

```r
# Set up blank pkg
usethis::create_package(file.path(tempdir(), "hadley"))
# Use `testthat`
usethis::use_testthat(3)

# Make test file
cat(file = testthat::test_path("test-new-file.R"), '
test_that("snapshot file still exists", {
  tmpfile <- tempfile(fileext = ".json")
  jsonlite::write_json(runif(10), tmpfile, pretty = TRUE)
  expect_snapshot_file(
    tmpfile,
    name = "runif-10.json",
    cran = FALSE,
    variant = NULL,
    compare = compare_file_text
  )
})
')
```

```r
# Init snapshot
devtools::test()
#> ℹ Loading hadley
#> ℹ Testing hadley
#> ✔ | F W S  OK | Context
#> ✔ |   1     1 | new-file
#> ───────────────────────────
#> Warning (test-new-file.R:5:3): snapshot file still exists
#> Adding new file snapshot: '_snaps/new-file/runif-10.json'
#> ───────────────────────────
#> 
#> ══ Results ══════════════════════════
#> [ FAIL 0 | WARN 1 | SKIP 0 | PASS 1 ]
```

```r
# Run again to produce error
devtools::test()
#> ℹ Loading hadley
#> ℹ Testing hadley
#> ✔ | F W S  OK | Context
#> ✖ | 1       0 | new-file
#> ─────────────────────────
#> Failure (test-new-file.R:5:3): snapshot file still exists
#> Snapshot of `tmpfile` to 'new-file/runif-10.json' has changed
#> Run `testthat::snapshot_review('new-file')` to review changes
#> ─────────────────────────
#> 
#> ══ Results ══════════════════════════
#> [ FAIL 1 | WARN 0 | SKIP 0 | PASS 0 ]
#> Deleting unused snapshots:
#> * new-file/runif-10.new.json
```

### PR DESCRIPTION
**Pull request by hadley**
Fixes #1462

@schloerke do you mind double checking this fixes your original problem?

### CODE REVIEW

**Comment by schloerke** [comment]
This fix does not delete my new files! Thank you!

**Comment by schloerke** [comment]
Related note, `new` files are not being overwritten with a newer `new` content. 

The first _new_ file content is being kept. Followup runs are not overwriting the content of the _new_ files

Ex: Running the test twice does not update the content in `_snaps/hadley/time.txt`

```r
# test-hadley.R
test_that("snapshot file still exists", {
  tmpfile <- tempfile(fileext = ".txt")
  cat(as.character(Sys.time()), "\n", file = tmpfile, sep = "")
  # Display contents to help with verification
  cat("New file should contain:\n", readLines(tmpfile), "\n", sep = "")
  expect_snapshot_file(
    tmpfile,
    name = "time.txt"
  )
})
```

**Comment by hadley** [comment]
@schloerke that doesn't seem to be a regression; I guess it never worked!

**Comment by schloerke** [comment]
> I guess it never worked!

Agreed. 

---------------

Thank you for the quick turn around on all of these issues. 😃😃

**Comment by hadley** [comment]
Don't take it personally, you're just lucky I'm trying to get a release out 😛

**Comment by schloerke** [comment]
😉 

---------------

> I'm trying to get a release out

Related: Can [you] also release `diffviewer` so that some pixels are not ignored? https://github.com/r-lib/diffviewer/issues/15

**Pull request merged**
