### PR TITLE
namespace hint?

### PR DESCRIPTION
**Pull request by maelle**
Like https://github.com/r-lib/testthat/blob/f8ccf033a74d89e2d1d3cb2ec3c6c4f63ca69055/R/snapshot-file.R#L144, for easier use by copy-pasting :-)

### CODE REVIEW

**Comment by hadley** [comment]
Why isn't testthat attached for you? `load_all()` will automatically attach it.

**Comment by maelle** [comment]
Right, maybe it happens in cases where I don't load_all() before testing? Or maybe I should close this PR. :see_no_evil:

**Comment by maelle** [comment]
I can confirm it happens because I don't necessarily run `load_all()` before running the tests (Ctrl + Alt + T).

**Comment by maelle** [comment]
To add a bit more context, it is a package for which I actually nearly never run `load_all()`, all tests happen in temporary projects. So I'd appreciate the namespace, but understand it might be too niche.

**Comment by hadley** [comment]
Lets leave this as is; at least for me it's a useful hint to run `load_all()`.

**Pull request closed without merging**
