### PR TITLE
jUnitReporter for integration with Jenkins CI

### PR DESCRIPTION
**Pull request by floybix**
Hi Hadley

Please take a look at this attempt to make a Jenkins-compatible output from test_that. As mentioned, I needed to stably identify tests irrespective of whether they are passing or failing, and so modified expect_that to store the call itself. It also substitutes the "info" argument if given to differentiate such tests (typically in a loop). This works for expect_that but not for the wrappers like expect_equals etc.

To fit into the jUnit structure, context() becomes the `<testsuite>` name as well as the base of the `<testcase>` classname. The test_that() name becomes the rest of the `<testcase>` classname. The deparsed expect_that() call becomes the `<testcase>` name. On failure, the message goes into the `<failure>` node message argument (first line only) and into its text content (full message).

Execution time is also recorded.

I have tested with Jenkins on my local machine.

Best
Felix

### CODE REVIEW

**Comment by jasonpbecker** [comment]
@floybix I would really appreciate this as I am using CircleCI which supports jUnit as well.

**Comment by floybix** [comment]
Hi, at this stage I haven't used R for more than a year, this isn't on my
radar any more. But feel free to take it over if you like.


On Saturday, March 7, 2015, Jason Becker <notifications@github.com> wrote:

> @floybix <https://github.com/floybix> I would really appreciate this as I
> am using CircleCI which supports jUnit as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hadley/testthat/pull/23#issuecomment-77622626>.
>


-- 
Felix Andrews / 安福立
http://www.neurofractal.org/felix/

**Comment by jspitzen** [comment]
Just to let you guys know, I have actually been using this fork for a while now. It's not perfect, but when one of our analysts messes up their R code, he gets an 'angry' email and a stormy cloud!

I have a feeling this is quite close to being 'finished' and I would like to offer my help in finishing it if that would be appreciated.

**Comment by hadley** [comment]
@jspitzen that would be great!

**Comment by jspitzen** [comment]
Above are obviously just references to my own personal to-do's regarding this ticket. @hadley and @floybix, if you can give me any pointers as to what still needs to happen to make this a part of test_that, that would be great!

**Comment by hadley** [comment]
@jspitzen best thing would be to do a new pull request, and I can give detailed comments on your code there

**Pull request closed without merging**
