### PR TITLE
add expect_no_match()

### LINKED ISSUE #1380: Add expect_no_match
This FR is to have a complete function to expect_match that handles the negative case. This is a pattern that exists in other frameworks. Here's an example from python:
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertNotRegex

I have a working version of this. Would you be interested in a patch?

### PR DESCRIPTION
**Pull request by michaelquinn32**
Fixes #1380

### CODE REVIEW

**Comment by michaelquinn32** [comment]
@MichaelChirico Let me know if this lines up with what you were thinking re `grep()` and `grepl()`

**Comment by MichaelChirico** [comment]
Yep that's what I had in mind, thanks!

**Comment by hadley** [comment]
I’d prefer to not use `grep()` and keep the change minimal so I don’t need to review the source code of grepl/grep to ensure there aren’t any unhappy surprises. .

**Comment by MichaelChirico** [comment]
FWIW I looked into why grepl doesn't have an invert argument recently and know their sources are very tightly coupled...

but fair point -- I will try and put the backend to grep() in a different PR if so desired

**Comment by michaelquinn32** [comment]
SGTM. Thanks for the feedback Hadley!

**Review by hadley — APPROVED** [review]
Can you please add a bullet to the top of `NEWS.md`? It should briefly [describe the change](http://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`.

**Comment by michaelquinn32** [comment]
Friendly ping!

Is there anything else that I can do here?

**Pull request merged**
