### PR TITLE
add skipped message to JUnit Reporter

### PR DESCRIPTION
**Pull request by rfineman**
Added the skipped test message to output when using JunitReporter.

### CODE REVIEW

**Comment by hadley** [comment]
@rfineman did you run this on windows? It looks like the line endings in the snapshot test got messed up, which is probably a testthat buglet.

**Comment by rfineman** [comment]
@hadley yeah ran on windows. apologies if that bugged out the snapshot

**Comment by hadley** [comment]
It's definitely my fault, not yours!

**Comment by hadley** [comment]
Thanks!

**Pull request merged**
